
SELECT DISTINCT ?resourceUri   
                
WHERE {  
{  
?resourceUri <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://purl.org/net/faunistics#Family>  
}  
                UNION {  
?resourceUri <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://purl.org/net/faunistics#Genus>  
}  
                UNION {  
?resourceUri <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://purl.org/net/faunistics#Species>  
}  
                UNION {  
?resourceUri <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://purl.org/net/faunistics#Order>  
}  
                UNION {  
?resourceUri <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://purl.org/net/faunistics#SubOrder>  
}  
                 
} LIMIT 1 
 