#fails: bind not implemented 
SELECT distinct ?x { 
    ?s <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/productPropertyTextual1>  ?o.
    BIND ("somestring"@en as ?x) 
    FILTER (?x != ?s ) 
}

ORDER BY ?s 

limit 10