#!/bin/bash 
SCRIPT=`readlink -f $0`
SCRIPTPATH=`dirname $SCRIPT`


cd $SCRIPTPATH/..

SCRIPTPATHPARENT=$PWD

echo "Starting SparqlMap...." >&2
#textdb.allow_full_path=false allows access to the full file system, see:  http://www.hsqldb.org/doc/guide/texttables-chapt.html
java  -classpath "lib/sparqlmap/*:lib/deps/*:lib/dbs/*" -Dtextdb.allow_full_path=true sparqlmap  $*
